# Generated by Django 3.1.13 on 2021-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_people", "0006_auto_20211107_2052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                help_text="You can add a company name here too if appropriate.",
                max_length=250,
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="fullname"
            ),
        ),
    ]
