# Generated by Django 3.2.9 on 2021-11-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_people", "0009_auto_20211113_1938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
