# Generated by Django 4.2.11 on 2024-10-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_people", "0013_alter_architect_architect_mentors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
