[tool.black]
extend-exclude = "mia_app/migrations"

[tool.pytest.ini_options]
pythonpath = [
    ".", "mia_app"
]
DJANGO_SETTINGS_MODULE = "mia_app.modernism.settings.dev"
log_cli = true
log_level = "WARN"
log_cli_level = "WARN"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%H:%M:%S"
addopts = "--strict-markers"
markers = [
    "the_one",
    "deactivated"
]
