# Generated by Django 3.1.13 on 2021-10-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mia_buildings', '0008_building_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='original_images'),
        ),
    ]
