# Generated by Django 3.1.13 on 2021-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mia_buildings', '0009_auto_20211024_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
