# Generated by Django 3.1.13 on 2021-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0010_auto_20211025_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="slug",
            field=models.SlugField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="subtitle",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="building",
            name="todays_use",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="constructiontype",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="facade",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="roof",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="window",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
