# Generated by Django 3.1.13 on 2021-10-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0011_auto_20211031_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="slug",
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
