# Generated by Django 4.2.4 on 2023-11-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0020_building_published_on_twitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingimage",
            name="image_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
