# Generated by Django 4.2.11 on 2024-10-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0022_building_name_addition"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="thumbnails_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
