# Generated by Django 4.2.11 on 2024-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0023_building_thumbnails_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="buildingimage",
            name="is_feed_image",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="buildingimage",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
