# Generated by Django 4.2.11 on 2024-10-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0024_alter_building_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="thumbnails_created",
        ),
        migrations.AddField(
            model_name="buildingimage",
            name="thumbnails_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
