# Generated by Django 4.2.17 on 2024-12-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mia_buildings', '0026_alter_buildingimage_thumbnails_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='published_on_twitter',
        ),
    ]
