# Generated by Django 3.0.5 on 2020-05-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0002_architectpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectpage',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='architectpage',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
