# Generated by Django 3.2.9 on 2021-11-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0015_auto_20211118_2231"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingimage",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
