# Generated by Django 3.2.9 on 2021-11-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0016_buildingimage_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildingimage",
            options={"ordering": ["image_order"]},
        ),
        migrations.AddField(
            model_name="buildingimage",
            name="image_order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
