# Generated by Django 3.2.10 on 2022-01-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0017_auto_20211124_2054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="buildingtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
