# Generated by Django 4.2.7 on 2024-01-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0021_alter_buildingimage_image_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="name_addition",
            field=models.CharField(
                blank=True,
                help_text="Add here the original name or info displayed in brackets behind the title. Do not add the brackets.",
                max_length=254,
            ),
        ),
    ]
