# Generated by Django 4.2.22 on 2025-10-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mia_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'To-Do Item', 'verbose_name_plural': 'To-Do Items'},
        ),
    ]
