# Generated by Django 3.1.13 on 2021-10-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mia_facts', '0003_auto_20211023_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factcategory',
            old_name='category',
            new_name='name',
        ),
    ]
