# Generated by Django 3.2.10 on 2022-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_facts", "0009_alter_city_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="seo_title",
            field=models.CharField(blank=True, max_length=61),
        ),
    ]
