# Generated by Django 3.1.13 on 2021-11-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mia_facts", "0007_auto_20211107_2128"),
        ("mia_people", "0007_auto_20211113_1556"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="birth_place_people",
                to="mia_facts.city",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="death_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="death_place_people",
                to="mia_facts.city",
            ),
        ),
    ]
