# Generated by Django 4.2.4 on 2023-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_people", "0012_person_seo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="architect_mentors",
            field=models.ManyToManyField(blank=True, to="mia_people.architect"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="professor_mentors",
            field=models.ManyToManyField(blank=True, to="mia_people.professor"),
        ),
    ]
