# Generated by Django 3.1.12 on 2021-08-06 18:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("people", "0003_auto_20200705_1938"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="architectpage",
            name="architect_mentors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="_architectpage_architect_mentors_+",
                to="people.ArchitectPage",
            ),
        ),
        migrations.CreateModel(
            name="ProfessorPage",
            fields=[
                (
                    "personpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="people.personpage",
                    ),
                ),
                (
                    "is_active_architect",
                    models.BooleanField(
                        default=False,
                        help_text="Is/Was the professor active as modernist archictect?",
                    ),
                ),
                (
                    "is_active_developer",
                    models.BooleanField(
                        default=False,
                        help_text="Is/Was the professor active as developer?",
                    ),
                ),
                (
                    "architect_mentors",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="people.ArchitectPage"
                    ),
                ),
                (
                    "professor_mentors",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="_professorpage_professor_mentors_+",
                        to="people.ProfessorPage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("people.personpage",),
        ),
        migrations.AddField(
            model_name="architectpage",
            name="professor_mentors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="people.ProfessorPage"
            ),
        ),
    ]
