# Generated by Django 3.1.12 on 2021-08-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0016_auto_20210807_1659"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("people", "0005_auto_20210806_2111"),
    ]

    operations = [
        migrations.RemoveField(model_name="buildingownersindexpage", name="page_ptr",),
        migrations.DeleteModel(name="BuildingOwnerPage",),
        migrations.DeleteModel(name="BuildingOwnersIndexPage",),
    ]
