# Generated by Django 3.2.10 on 2022-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_people", "0011_auto_20211118_2313"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="seo_title",
            field=models.CharField(blank=True, max_length=61),
        ),
    ]
