# Generated by Django 3.0.5 on 2020-05-25 15:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20200524_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpage',
            name='gallery_images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.TextBlock(required=False)), ('photographer', wagtail.core.blocks.CharBlock(required=False))], blank=True),
        ),
    ]
