# Generated by Django 3.0.5 on 2020-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_auto_20200705_1938"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Access types",},
        ),
    ]
