# Generated by Django 3.0.5 on 2020-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200525_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='buildingpage',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
