# Generated by Django 3.0.5 on 2020-07-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_accesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpage',
            name='access_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.AccessType'),
        ),
    ]
