# Generated by Django 3.1.6 on 2021-02-27 21:49

import buildings.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0007_auto_20200705_2252"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingtype",
            name="description",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="buildingpage",
            name="gallery_images",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", buildings.blocks.ImageChooserBlock()),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(required=False),
                                ),
                                (
                                    "photographer",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
