# Generated by Django 3.1.8 on 2021-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0008_auto_20210227_2149"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingpage",
            name="protected_monument",
            field=models.BooleanField(default=False),
        ),
    ]
