# Generated by Django 3.1.8 on 2021-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0009_buildingpage_protected_monument"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingpage",
            name="storey",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
