# Generated by Django 3.1.8 on 2021-05-13 20:14

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0012_buildingpage_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingpage",
            name="construction_types",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="buildings.ConstructionType"
            ),
        ),
        migrations.AddField(
            model_name="buildingpage",
            name="details",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="buildings.Detail"
            ),
        ),
        migrations.AddField(
            model_name="buildingpage",
            name="facades",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="buildings.Facade"
            ),
        ),
        migrations.AddField(
            model_name="buildingpage",
            name="roofs",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="buildings.Roof"
            ),
        ),
        migrations.AddField(
            model_name="buildingpage",
            name="windows",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="buildings.Window"
            ),
        ),
    ]
