# Generated by Django 3.1.12 on 2021-08-07 08:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20210806_2111"),
        ("buildings", "0013_auto_20210513_2014"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingpage",
            name="related_architects",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="related_buildings", to="people.ArchitectPage"
            ),
        ),
        migrations.AddField(
            model_name="buildingpage",
            name="related_developers",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="related_buildings", to="people.DeveloperPage"
            ),
        ),
    ]
