# Generated by Django 3.1.12 on 2021-08-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0015_add_architects_developers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="buildingpagedeveloperrelation", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="buildingpagedeveloperrelation", name="developer",
        ),
        migrations.RemoveField(
            model_name="buildingpagedeveloperrelation", name="page",
        ),
        migrations.AlterUniqueTogether(
            name="buildingpageownerrelation", unique_together=None,
        ),
        migrations.RemoveField(model_name="buildingpageownerrelation", name="owner",),
        migrations.RemoveField(model_name="buildingpageownerrelation", name="page",),
        migrations.DeleteModel(name="BuildingPageArchitectRelation",),
        migrations.DeleteModel(name="BuildingPageDeveloperRelation",),
        migrations.DeleteModel(name="BuildingPageOwnerRelation",),
    ]
