# Generated by Django 3.1.13 on 2021-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mia_buildings", "0012_auto_20211031_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="slug",
            field=models.SlugField(blank=True, max_length=254),
        ),
    ]
