# Generated by Django 4.2.22 on 2025-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mia_buildings', '0028_buildingimage_todo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimage',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
