name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Tag to build the dev image from'
        required: true
jobs:
  dev-build-and-push:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Tag Format
      id: validate_tag
      run: |
        if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid tag format: ${GITHUB_REF_NAME}"
          exit 1
        fi
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image with docker compose
      run: |
        docker compose -f docker/compose.ci.yaml \
          build --build-arg PLATFORM=dev
      shell: bash
    
    - name: Push Docker Image to Registry
      run: |
        IMAGE_NAME="ghcr.io/modernism-in-architecture/mia-django-dev"
        docker tag mia-django ${IMAGE_NAME}:${{ github.ref_name }}
        docker push ${IMAGE_NAME}:${{ github.ref_name }}
      shell: bash
